spring:
  datasource:
    url: jdbc:h2:mem:planetdb
    username: sun
    password: password
    driverClassName: org.h2.Driver
  
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations:
      - classpath:db/schema.sql
      data-locations:
      - classpath:db/data.sql